service: adv-intimacoes

frameworkVersion: "4"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  profile: adv-intimacoes
  environment:
    GOOGLE_CREDENTIALS: ${env:GOOGLE_CREDENTIALS} 
    API_KEY: ${env:API_KEY} 
    NODE_ENV: production
    MEGA_API_URL: ${env:MEGA_API_URL}
    MEGA_API_KEY: ${env:MEGA_API_KEY}
    MEGA_API_TOKEN: ${env:MEGA_API_TOKEN}
    DATABASE_URL: ${env:DATABASE_URL}

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

functions:
  processIntimacoes:
    handler: src/index.handler
    timeout: 300
    events:
      - schedule:
          rate: cron(*/20 9-21 ? * MON-FRI *)
          enabled: true
          description: "Processa intimações todos os dias da semana (9h-18h)"

  api:
    handler: src/api-lambda.handler
    timeout: 29
    events:
      - http:
          path: /health
          method: get
          cors: true
      - http:
          path: /api/intimacoes
          method: get
          cors: true
      - http:
          path: /api/webhook/whatsapp
          method: post
          cors: true
